repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:2.0.1
  gwt_user: com.google.gwt:gwt-user:jar:2.5.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.5.1

  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA

  # This dependency demonstrates that appcache can work even when caching disabled
  # for the resources within the manifest. Firefox disallows no-store in Cache-control
  # header.
  gwt_cache_filter: org.realityforge.gwt.cache-filter:gwt-cache-filter:jar:0.3

  gwt_appcache_client: org.realityforge.gwt.appcache:gwt-appcache-client:jar:1.0.4
  gwt_appcache_linker: org.realityforge.gwt.appcache:gwt-appcache-linker:jar:1.0.4
  gwt_appcache_server: org.realityforge.gwt.appcache:gwt-appcache-server:jar:1.0.4
